In [7]:
#RIPASSO SU DATI E FREQUENZE CON UN DATASET TROVATO SU KAGGLE RELATIVO ALLE AUTO ELETTRICHE A WASHINGTON

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

cars = pd.read_csv('dataset_concessionaria.csv', sep = ',', index_col = 0)
cars

,Marca,Modello,Anno,Prezzo,Colore,Chilometraggio,Numero_di_Proprietari,Trasmissione,Motorizzazione,Cavalli,Vel_Max,Accelerazione
ID,,,,,,,,,,,,
1,Audi,RS6,2001,48455,Nero,23420,2,Automatico,Benzina,928,304,8.96
2,BMW,Jetta,2023,31497,Argento,18937,3,Automatico,Benzina,1234,269,5.04
3,Audi,Civic,2018,22404,Rosso,147054,2,Automatico,Elettrica,918,240,7.19
4,Ford,Altima,2011,31970,Rosso,102946,0,Automatico,Ibrida,699,211,9.58
5,Ford,Focus,2000,37060,Rosso,60846,5,Automatico,Ibrida,949,239,3.93
...,...,...,...,...,...,...,...,...,...,...,...,...
996,Nissan,RS6,2010,46825,Blu,92521,1,Manuale,Benzina,1369,220,3.77
997,Nissan,C-Class,2016,33104,Argento,41212,0,Automatico,Ibrida,273,195,3.18
998,Honda,Altima,2001,27589,Rosso,14401,5,Manuale,Benzina,574,304,5.33
999,Volkswagen,Civic,2012,48596,Nero,43000,0,Automatico,Diesel,517,258,8.21
1000,Ford,C-Class,2008,10484,Bianco,137059,1,Automatico,Elettrica,379,250,6.78